Construct and use terraform.tfvars.json

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -46,6 +46,8 @@ stages:
                   echo "${{ build.product_version }}"
                   echo "${{ build.kubernetes_version }}"
                   echo "${{ build.secret_bucket }}"
+                  #use single quotes with complex objects!
+                  echo '${{ convertToJson(build.features) }}'
 
   - stage: plan
     pool: 
@@ -80,6 +82,12 @@ stages:
               inputs:
                 secureFile: 'gh_secrets.tfvars'
 
+            - task: DownloadSecureFile@1
+              name: open_server
+              displayName: 'open server'
+              inputs:
+                secureFile: 'open_server.sh'
+
             - task: AWSShellScript@1
               name: terraformPlanApply
               inputs:
@@ -98,11 +106,281 @@ stages:
                   export TF_VAR_kubernetes_version="${{ build.kubernetes_version }}"
                   export TF_VAR_secret_bucket="${{ build.secret_bucket }}"
 
+                  #use single quotes with complex objects!
+                  export features='${{ convertToJson(build.features) }}'
+                  jq --argjson x "$features" '{features:$x}' <<< '{}' > terraform.tfvars.json
+
                   touch kubeconfig
                   terraform init
                   export TF_WORKSPACE=$TF_VAR_client_name-$TF_VAR_product_version-$TF_VAR_metro
-                  terraform plan -compact-warnings -var-file=./workloads.tfvars -var-file=$(gh_secrets.secureFilePath)
-                  terraform apply -auto-approve -compact-warnings -var-file=./workloads.tfvars -var-file=$(gh_secrets.secureFilePath)
+                  terraform plan -compact-warnings \
+                                 -var-file=./workloads.tfvars \
+                                 -var-file=$(gh_secrets.secureFilePath)
+
+                  terraform apply -auto-approve -compact-warnings \
+                                  -var-file=./workloads.tfvars \
+                                  -var-file=$(gh_secrets.secureFilePath)
+
+                failOnStdErr: true
+                targetType: inline
+                workingDirectory: $(Build.SourcesDirectory)
+
+            - task: AWSShellScript@1
+              name: checkStatusBaseline01
+              inputs:
+                awsCredentials: aws-apl
+                regionName: ap-southeast-2
+                scriptType: inline
+                inlineScript: |
+                  sudo apt-get install knockd
+
+                  export TF_VAR_auth_token="${{ build.auth_token }}"
+                  export TF_VAR_aws_role_arn="${{ build.aws_role_arn }}"
+                  export TF_VAR_ccm_enabled="${{ build.ccm_enabled }}"
+                  export TF_VAR_client_name="${{ build.client_name }}"
+                  export TF_VAR_count_x86="${{ build.count_x86 }}"
+                  export TF_VAR_domain_name=$(TF_VAR_domain_name)
+                  export TF_VAR_metro="${{ build.metro }}"
+                  export TF_VAR_product_version="${{ build.product_version }}"
+                  export TF_VAR_kubernetes_version="${{ build.kubernetes_version }}"
+                  export TF_VAR_secret_bucket="${{ build.secret_bucket }}"
+                  export KUBECONFIG=$PWD/kubeconfig
+
+                  #use single quotes with complex objects!
+                  export features='${{ convertToJson(build.features) }}'
+                  jq --argjson x "$features" '{features:$x}' <<< '{}' > terraform.tfvars.json
+
+                  touch kubeconfig
+                  terraform init
+                  export TF_WORKSPACE=$TF_VAR_client_name-$TF_VAR_product_version-$TF_VAR_metro
+
+                  kubernetes_api_address=$(sed -e 's/^"//' -e 's/"$//' <<< $(terraform output kubernetes_api_address))
+                  echo $kubernetes_api_address
+
+                  knock -d 100 $kubernetes_api_address 600:udp 606:udp 666:udp || echo "knock failed"
+                  knock -d 200 $kubernetes_api_address 600:udp 606:udp 666:udp && echo "knock succeeded"
+
+                  terraform taint 'null_resource.download_defined_secrets_from_s3["kubeconfig"]'
+                  terraform apply -auto-approve -compact-warnings \
+                                  -var-file=./workloads.tfvars \
+                                  -var-file=$(gh_secrets.secureFilePath) \
+                                  -target='null_resource.download_defined_secrets_from_s3["kubeconfig"]'
+
+                  kubectl get all
+                  terraform apply -auto-approve -compact-warnings \
+                                  -var-file=./workloads.tfvars \
+                                  -var-file=$(gh_secrets.secureFilePath) \
+                                  -var-file 'services/01-base-services.tfvars'
+                failOnStdErr: true
+                targetType: inline
+                workingDirectory: $(Build.SourcesDirectory)
+
+            - task: AWSShellScript@1
+              name: checkStatusBaseline02
+              inputs:
+                awsCredentials: aws-apl
+                regionName: ap-southeast-2
+                scriptType: inline
+                inlineScript: |
+                  sudo apt-get install knockd
+
+                  export TF_VAR_auth_token="${{ build.auth_token }}"
+                  export TF_VAR_aws_role_arn="${{ build.aws_role_arn }}"
+                  export TF_VAR_ccm_enabled="${{ build.ccm_enabled }}"
+                  export TF_VAR_client_name="${{ build.client_name }}"
+                  export TF_VAR_count_x86="${{ build.count_x86 }}"
+                  export TF_VAR_domain_name=$(TF_VAR_domain_name)
+                  export TF_VAR_metro="${{ build.metro }}"
+                  export TF_VAR_product_version="${{ build.product_version }}"
+                  export TF_VAR_kubernetes_version="${{ build.kubernetes_version }}"
+                  export TF_VAR_secret_bucket="${{ build.secret_bucket }}"
+                  export KUBECONFIG=$PWD/kubeconfig
+
+                  #use single quotes with complex objects!
+                  export features='${{ convertToJson(build.features) }}'
+                  jq --argjson x "$features" '{features:$x}' <<< '{}' > terraform.tfvars.json
+
+                  touch kubeconfig
+                  terraform init
+                  export TF_WORKSPACE=$TF_VAR_client_name-$TF_VAR_product_version-$TF_VAR_metro
+
+                  kubernetes_api_address=$(sed -e 's/^"//' -e 's/"$//' <<< $(terraform output kubernetes_api_address))
+                  echo $kubernetes_api_address
+
+                  knock -d 100 $kubernetes_api_address 600:udp 606:udp 666:udp || echo "knock failed"
+                  knock -d 200 $kubernetes_api_address 600:udp 606:udp 666:udp && echo "knock succeeded"
+
+                  terraform taint 'null_resource.download_defined_secrets_from_s3["kubeconfig"]'
+                  terraform apply -auto-approve -compact-warnings \
+                                  -var-file=./workloads.tfvars \
+                                  -var-file=$(gh_secrets.secureFilePath) \
+                                  -target='null_resource.download_defined_secrets_from_s3["kubeconfig"]'
+
+                  kubectl get all
+                  terraform apply -auto-approve -compact-warnings \
+                                  -var-file=./workloads.tfvars \
+                                  -var-file=$(gh_secrets.secureFilePath) \
+                                  -var-file 'services/01-base-services.tfvars' \
+                                  -var-file 'services/02-base-services.tfvars'
+                failOnStdErr: true
+                targetType: inline
+                workingDirectory: $(Build.SourcesDirectory)
+
+            - task: AWSShellScript@1
+              name: checkStatusConfluent03
+              inputs:
+                awsCredentials: aws-apl
+                regionName: ap-southeast-2
+                scriptType: inline
+                inlineScript: |
+                  sudo apt-get install knockd
+
+                  export TF_VAR_auth_token="${{ build.auth_token }}"
+                  export TF_VAR_aws_role_arn="${{ build.aws_role_arn }}"
+                  export TF_VAR_ccm_enabled="${{ build.ccm_enabled }}"
+                  export TF_VAR_client_name="${{ build.client_name }}"
+                  export TF_VAR_count_x86="${{ build.count_x86 }}"
+                  export TF_VAR_domain_name=$(TF_VAR_domain_name)
+                  export TF_VAR_metro="${{ build.metro }}"
+                  export TF_VAR_product_version="${{ build.product_version }}"
+                  export TF_VAR_kubernetes_version="${{ build.kubernetes_version }}"
+                  export TF_VAR_secret_bucket="${{ build.secret_bucket }}"
+                  export KUBECONFIG=$PWD/kubeconfig
+
+                  #use single quotes with complex objects!
+                  export features='${{ convertToJson(build.features) }}'
+                  jq --argjson x "$features" '{features:$x}' <<< '{}' > terraform.tfvars.json
+
+                  touch kubeconfig
+                  terraform init
+                  export TF_WORKSPACE=$TF_VAR_client_name-$TF_VAR_product_version-$TF_VAR_metro
+
+                  kubernetes_api_address=$(sed -e 's/^"//' -e 's/"$//' <<< $(terraform output kubernetes_api_address))
+                  echo $kubernetes_api_address
+
+                  knock -d 100 $kubernetes_api_address 600:udp 606:udp 666:udp || echo "knock failed"
+                  knock -d 200 $kubernetes_api_address 600:udp 606:udp 666:udp && echo "knock succeeded"
+
+                  terraform taint 'null_resource.download_defined_secrets_from_s3["kubeconfig"]'
+                  terraform apply -auto-approve -compact-warnings \
+                                  -var-file=./workloads.tfvars \
+                                  -var-file=$(gh_secrets.secureFilePath) \
+                                  -target='null_resource.download_defined_secrets_from_s3["kubeconfig"]'
+
+                  kubectl get all
+                  terraform apply -auto-approve -compact-warnings \
+                                  -var-file=./workloads.tfvars \
+                                  -var-file=$(gh_secrets.secureFilePath) \
+                                  -var-file 'services/01-base-services.tfvars' \
+                                  -var-file 'services/02-base-services.tfvars' \
+                                  -var-file 'services/03-confluent-services.tfvars'
+                failOnStdErr: true
+                targetType: inline
+                workingDirectory: $(Build.SourcesDirectory)
+
+            - task: AWSShellScript@1
+              name: checkStatusObservability04
+              inputs:
+                awsCredentials: aws-apl
+                regionName: ap-southeast-2
+                scriptType: inline
+                inlineScript: |
+                  sudo apt-get install knockd
+
+                  export TF_VAR_auth_token="${{ build.auth_token }}"
+                  export TF_VAR_aws_role_arn="${{ build.aws_role_arn }}"
+                  export TF_VAR_ccm_enabled="${{ build.ccm_enabled }}"
+                  export TF_VAR_client_name="${{ build.client_name }}"
+                  export TF_VAR_count_x86="${{ build.count_x86 }}"
+                  export TF_VAR_domain_name=$(TF_VAR_domain_name)
+                  export TF_VAR_metro="${{ build.metro }}"
+                  export TF_VAR_product_version="${{ build.product_version }}"
+                  export TF_VAR_kubernetes_version="${{ build.kubernetes_version }}"
+                  export TF_VAR_secret_bucket="${{ build.secret_bucket }}"
+                  export KUBECONFIG=$PWD/kubeconfig
+
+                  #use single quotes with complex objects!
+                  export features='${{ convertToJson(build.features) }}'
+                  jq --argjson x "$features" '{features:$x}' <<< '{}' > terraform.tfvars.json
+
+                  touch kubeconfig
+                  terraform init
+                  export TF_WORKSPACE=$TF_VAR_client_name-$TF_VAR_product_version-$TF_VAR_metro
+
+                  kubernetes_api_address=$(sed -e 's/^"//' -e 's/"$//' <<< $(terraform output kubernetes_api_address))
+                  echo $kubernetes_api_address
+
+                  knock -d 100 $kubernetes_api_address 600:udp 606:udp 666:udp || echo "knock failed"
+                  knock -d 200 $kubernetes_api_address 600:udp 606:udp 666:udp && echo "knock succeeded"
+
+                  terraform taint 'null_resource.download_defined_secrets_from_s3["kubeconfig"]'
+                  terraform apply -auto-approve -compact-warnings \
+                                  -var-file=./workloads.tfvars \
+                                  -var-file=$(gh_secrets.secureFilePath) \
+                                  -target='null_resource.download_defined_secrets_from_s3["kubeconfig"]'
+
+                  kubectl get all
+                  terraform apply -auto-approve -compact-warnings \
+                                  -var-file=./workloads.tfvars \
+                                  -var-file=$(gh_secrets.secureFilePath) \
+                                  -var-file 'services/01-base-services.tfvars' \
+                                  -var-file 'services/02-base-services.tfvars' \
+                                  -var-file 'services/03-confluent-services.tfvars' \
+                                  -var-file 'services/04-observability-services.tfvars'
+                failOnStdErr: true
+                targetType: inline
+                workingDirectory: $(Build.SourcesDirectory)
+
+            - task: AWSShellScript@1
+              name: checkStatusL3a
+              inputs:
+                awsCredentials: aws-apl
+                regionName: ap-southeast-2
+                scriptType: inline
+                inlineScript: |
+                  sudo apt-get install knockd
+
+                  export TF_VAR_auth_token="${{ build.auth_token }}"
+                  export TF_VAR_aws_role_arn="${{ build.aws_role_arn }}"
+                  export TF_VAR_ccm_enabled="${{ build.ccm_enabled }}"
+                  export TF_VAR_client_name="${{ build.client_name }}"
+                  export TF_VAR_count_x86="${{ build.count_x86 }}"
+                  export TF_VAR_domain_name=$(TF_VAR_domain_name)
+                  export TF_VAR_metro="${{ build.metro }}"
+                  export TF_VAR_product_version="${{ build.product_version }}"
+                  export TF_VAR_kubernetes_version="${{ build.kubernetes_version }}"
+                  export TF_VAR_secret_bucket="${{ build.secret_bucket }}"
+                  export KUBECONFIG=$PWD/kubeconfig
+
+                  #use single quotes with complex objects!
+                  export features='${{ convertToJson(build.features) }}'
+                  jq --argjson x "$features" '{features:$x}' <<< '{}' > terraform.tfvars.json
+
+                  touch kubeconfig
+                  terraform init
+                  export TF_WORKSPACE=$TF_VAR_client_name-$TF_VAR_product_version-$TF_VAR_metro
+
+                  kubernetes_api_address=$(sed -e 's/^"//' -e 's/"$//' <<< $(terraform output kubernetes_api_address))
+                  echo $kubernetes_api_address
+
+                  knock -d 100 $kubernetes_api_address 600:udp 606:udp 666:udp || echo "knock failed"
+                  knock -d 200 $kubernetes_api_address 600:udp 606:udp 666:udp && echo "knock succeeded"
+
+                  terraform taint 'null_resource.download_defined_secrets_from_s3["kubeconfig"]'
+                  terraform apply -auto-approve -compact-warnings \
+                                  -var-file=./workloads.tfvars \
+                                  -var-file=$(gh_secrets.secureFilePath) \
+                                  -target='null_resource.download_defined_secrets_from_s3["kubeconfig"]'
+
+                  kubectl get all
+                  terraform apply -auto-approve -compact-warnings \
+                                  -var-file=./workloads.tfvars \
+                                  -var-file=$(gh_secrets.secureFilePath) \
+                                  -var-file 'services/01-base-services.tfvars' \
+                                  -var-file 'services/02-base-services.tfvars' \
+                                  -var-file 'services/03-confluent-services.tfvars' \
+                                  -var-file 'services/04-observability-services.tfvars' \
+                                  -var-file 'services/10-l3a-services.tfvars'
                 failOnStdErr: true
                 targetType: inline
                 workingDirectory: $(Build.SourcesDirectory)
